embed_model: "llama.cpp/models/embeddings/nomic-embed-text-v1.5.Q4_K_S.gguf"
model_path: "llama.cpp/models/qwen2.5-0.5b-instruct-q5_k_m.gguf"

top_k: 12
pool_size: 120
ensemble_method: "rrf"
rrf_k: 60
ranker_weights: [1.0, 1.0]

chunk_mode: "sections"


system_prompt_mode: "tutor"
max_gen_tokens: 350
